name: Node.js Application Workflow
on: 
  workflow_dispatch:
  push:
    branches: 
      -  "master"
  pull_request:
      branches: ["master"]
jobs:
    intall-nodejs:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository code
          uses: actions/checkout@v6

        - name: install Node.js environment
          uses: actions/setup-node@v6
          with:
            node-version: '20'
            cache: 'npm'

        - name: Install dependencies
          run: npm ci

        - name: Run automated tests
          run: npm test

        - name: Build application
          run: npm run build --if-present
